import { GOOGLE_CLIENT_ID } from './config.js';
const app = document.querySelector('#app');
let user=null,peer=null,connection=null,remoteId='',activeCall=null,localStream=null,incomingCall=null,remoteName='Görüşme arkadaşın';
const joinId=new URLSearchParams(location.search).get('join')||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=s=>(s||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function login(){app.innerHTML=`<main class="login"><section class="art"><a class="brand">yakın<span>.</span></a><div class="art-copy"><small>YAKINLARINLA, NEREDE OLURSAN OL</small><h1>Bir tıkla<br><i>yan yana.</i></h1><p>Konuş. Görüş. Paylaş.<br>Mesafe ekranda kalsın.</p><div class="art-orbit"><b>Y</b><i></i><i></i></div></div><span class="art-foot">YAKIN · BİREBİR GÖRÜŞME</span></section><section class="login-side"><div class="login-top"><a class="brand mobile-brand">yakın<span>.</span></a><small>ANINDA BAĞLANTI</small></div><div class="login-card"><span class="eyebrow">BAĞLANTI KUR</span><h2>Görüşmeye<br>katıl.</h2><p>Google hesabınla giriş yap veya misafir olarak devam et.</p><div id="google-button"></div><div id="config-note" class="config-note"></div><div class="or"><span>YA DA</span></div><button id="guest" class="guest">Misafir olarak devam et <b>↗</b></button><p id="join-note" class="join-note">${joinId?'Davet bağlantısı hazır. Devam edince odaya katılacaksın.':'Bir oda aç, davet bağlantını arkadaşına gönder.'}</p></div><small class="foot-note">UÇTAN UCA WEBRTC · ANLIK MESAJLAR</small></section></main>`;
 document.querySelector('#guest').onclick=()=>{user={name:'Misafir '+Math.floor(10+Math.random()*90),id:'guest-'+crypto.randomUUID()};start()};
 if(GOOGLE_CLIENT_ID&&!GOOGLE_CLIENT_ID.startsWith('YOUR_')){const wait=setInterval(()=>{if(window.google?.accounts?.id){clearInterval(wait);google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:r=>{try{const raw=atob(r.credential.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'));const data=JSON.parse(new TextDecoder().decode(Uint8Array.from(raw,c=>c.charCodeAt(0))));user={name:data.name||'Google kullanıcısı',picture:data.picture||'',id:data.sub};start()}catch{document.querySelector('#config-note').textContent='Google hesabı okunamadı. Tekrar dene.'}}});google.accounts.id.renderButton(document.querySelector('#google-button'),{theme:'outline',size:'large',shape:'rectangular',text:'continue_with',width:330,locale:'tr'})}},100)}else{document.querySelector('#config-note').innerHTML='Google girişi için <code>src/config.js</code> içine Web Client ID ekle. İstersen şimdi misafir olarak gir.'}
}
function start(){render();if(!window.Peer){toast('PeerJS bağlantısı yüklenemedi. Sayfayı yenile.',true);return}peer=new Peer(undefined,{debug:1,config:{iceServers:[{urls:'stun:stun.l.google.com:19302'}]}});peer.on('open',id=>{document.querySelector('#myid').textContent=id;status('Odan hazır','ok');if(joinId){document.querySelector('#peerid').value=joinId;connect()}});peer.on('connection',c=>attach(c));peer.on('call',call=>incoming(call));peer.on('error',e=>{status(e.type==='peer-unavailable'?'Oda bulunamadı':'Bağlantı hatası','bad');toast(e.type==='peer-unavailable'?'Arkadaşının odası açık mı kontrol et.':e.message,true)});}
function render(){const photo=user.picture?`<img src="${esc(user.picture)}" alt="">`:esc(initials(user.name));app.innerHTML=`<main class="app"><aside class="side"><div class="side-brand"><a class="brand">yakın<span>.</span></a><button id="logout" title="Çıkış">···</button></div><div class="profile"><span class="avatar">${photo}</span><div><b>${esc(user.name)}</b><small><i></i> ÇEVRİM İÇİ</small></div></div><div class="label">GÖRÜŞME ODAN</div><div class="room"><span>⌁</span><div><b>Oda kodun</b><small id="myid">Hazırlanıyor…</small></div></div><button id="invite" class="invite">Davet bağlantısını kopyala <b>↗</b></button><div class="label connect-label">ARKADAŞINA BAĞLAN</div><div class="join"><input id="peerid" placeholder="Davet kodu"><button id="connect">Git</button></div><small class="help">Davet linkini açınca bu alan otomatik dolar.</small><div class="side-foot">Bağlantı durumu: <b id="side-status">Hazırlanıyor</b></div></aside><section class="main"><header><div><small class="eyebrow">ÖZEL GÖRÜŞME</small><h1 id="title">Birini davet et.</h1></div><span class="status" id="status"><i></i> BAĞLANTI BEKLENİYOR</span></header><div class="stage"><div class="video-grid" id="grid"><div class="tile"><video id="remote" autoplay playsinline></video><div class="empty" id="empty"><span class="avatar big">${photo}</span><b id="remote-name">Arkadaşını bekliyoruz</b><small>Görüşme başlayınca burada görünecek</small></div><label id="tile-remote">Görüşme</label></div><div class="tile self"><video id="local" autoplay muted playsinline></video><div class="self-empty" id="self-empty">${esc(initials(user.name))}</div><label>Sen</label></div></div><div class="welcome" id="welcome"><div class="symbol">⌁</div><small class="eyebrow">ODA HAZIR</small><h2>Birlikte olmanın<br><i>en kısa yolu.</i></h2><p>Davet bağlantını gönder. Arkadaşın katılınca mesajlaşabilir ve görüşebilirsiniz.</p><button id="share-main" class="primary">Bağlantıyı paylaş <b>↗</b></button></div></div><footer><button id="mic" class="tool">♬<small>Mikrofon</small></button><button id="camera" class="tool">▣<small>Kamera</small></button><button id="audio-call" class="tool">☎<small>Ara</small></button><button id="hangup" class="tool red">☎<small>Kapat</small></button></footer></section><aside class="chat"><header><div><small class="eyebrow">BİREBİR SOHBET</small><h2>Mesajlar <span id="count">0</span></h2></div><i class="online"></i></header><div id="messages" class="messages"><div class="empty-chat"><b>Merhaba de.</b><p>Arkadaşın bağlanınca mesajlaşma burada başlayacak.</p></div></div><form id="form"><input id="text" placeholder="Mesaj yaz…" disabled autocomplete="off"><button id="send" disabled>↑</button></form><small class="chat-foot">Enter ile gönder</small></aside><div id="incoming" class="incoming hidden"></div><div id="toast" class="toast"></div></main>`;
 document.querySelector('#logout').onclick=()=>{stop();user=null;login()};document.querySelector('#invite').onclick=share;document.querySelector('#share-main').onclick=share;document.querySelector('#connect').onclick=connect;document.querySelector('#peerid').onkeydown=e=>{if(e.key==='Enter')connect()};document.querySelector('#form').onsubmit=send;document.querySelector('#mic').onclick=mic;document.querySelector('#camera').onclick=camera;document.querySelector('#audio-call').onclick=()=>call(false);document.querySelector('#hangup').onclick=hangup;
}
function status(text,type=''){const e=document.querySelector('#status');if(!e)return;e.innerHTML=`<i class="${type}"></i> ${esc(text.toLocaleUpperCase('tr'))}`;document.querySelector('#side-status').textContent=text}
function attach(c){connection=c;remoteId=c.peer;remoteName=c.metadata?.name||'Görüşme arkadaşın';c.on('open',()=>{document.querySelector('#text').disabled=false;document.querySelector('#send').disabled=false;document.querySelector('#title').textContent=remoteName+' ile bağlantı';document.querySelector('#remote-name').textContent=remoteName;document.querySelector('#tile-remote').textContent=remoteName;document.querySelector('#welcome').classList.add('hidden');status('Arkadaşın bağlandı','ok');toast('Bağlandınız. Mesajlaşmaya başlayın.')});c.on('data',d=>{if(d?.type==='message')addMessage(d.text,d.name||remoteName,false,d.at)});c.on('close',()=>{connection=null;document.querySelector('#text').disabled=true;document.querySelector('#send').disabled=true;status('Bağlantı sona erdi','bad')});c.on('error',e=>toast(e.message||'Mesaj gönderilemedi.',true))}
function connect(){const id=document.querySelector('#peerid').value.trim()||joinId;if(!id||!peer?.id){toast('Oda hazırlanıyor veya davet kodu eksik.');return}if(id===peer.id){toast('Kendi odana bağlanamazsın.',true);return}remoteId=id;status('Bağlanıyor…');attach(peer.connect(id,{reliable:true,metadata:{name:user.name}}))}
async function share(){if(!peer?.id){toast('Oda hazırlanıyor. Birkaç saniye bekle.');return}const u=new URL(location.href);u.search='';u.searchParams.set('join',peer.id);try{await navigator.clipboard.writeText(u.href);toast('Davet bağlantısı kopyalandı. Arkadaşına gönder!')}catch{prompt('Bu bağlantıyı arkadaşına gönder:',u.href)}}
function send(e){e.preventDefault();const input=document.querySelector('#text'),text=input.value.trim();if(!text||!connection?.open)return;connection.send({type:'message',text,name:user.name,at:Date.now()});addMessage(text,user.name,true,Date.now());input.value=''}
function addMessage(text,name,mine,at){const box=document.querySelector('#messages');box.querySelector('.empty-chat')?.remove();const row=document.createElement('div');row.className='message '+(mine?'mine':'');const time=new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(new Date(at||Date.now()));const meta=document.createElement('small');meta.textContent=(mine?'Sen':name)+' · '+time;const bubble=document.createElement('div');bubble.textContent=text;row.append(meta,bubble);box.append(row);box.scrollTop=box.scrollHeight;document.querySelector('#count').textContent=box.querySelectorAll('.message').length}
async function call(video){if(!remoteId){toast('Önce arkadaşını davet et veya oda kodunu gir.',true);return}try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video?{width:{ideal:1280},height:{ideal:720}}:false});showLocal();activeCall=peer.call(remoteId,localStream,{metadata:{video,name:user.name}});bindCall(activeCall,video)}catch(e){toast('Mikrofon/kamera izni gerekli: '+e.message,true)}}
function incoming(c){incomingCall=c;const name=c.metadata?.name||remoteName,video=!!c.metadata?.video;const box=document.querySelector('#incoming');box.classList.remove('hidden');box.innerHTML=`<div class="incoming-card"><span>☎</span><small class="eyebrow">GELEN ${video?'GÖRÜNTÜLÜ':'SESLİ'} ARAMA</small><h2>${esc(name)} arıyor</h2><p>Aramaya katılmak ister misin?</p><button id="decline">Reddet</button><button id="answer">Yanıtla</button></div>`;document.querySelector('#answer').onclick=()=>answer(video);document.querySelector('#decline').onclick=()=>{incomingCall?.close();incomingCall=null;box.classList.add('hidden')}}
async function answer(video){try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video?{width:{ideal:1280},height:{ideal:720}}:false});showLocal();activeCall=incomingCall;incomingCall=null;document.querySelector('#incoming').classList.add('hidden');activeCall.answer(localStream);bindCall(activeCall,video)}catch(e){toast('Mikrofon/kamera izni gerekli: '+e.message,true)}}
function bindCall(c,video){activeCall=c;c.on('stream',s=>{document.querySelector('#remote').srcObject=s;document.querySelector('#empty').classList.add('hidden');document.querySelector('#grid').classList.add('live');document.querySelector('#welcome').classList.add('hidden');document.querySelector('#camera').classList.toggle('active',video);status('Görüşme başladı','ok')});c.on('close',resetCall);c.on('error',e=>{toast(e.message||'Arama kesildi.',true);resetCall()})}
function showLocal(){document.querySelector('#local').srcObject=localStream;document.querySelector('#self-empty').classList.add('hidden');document.querySelector('#grid').classList.add('live')}
function resetCall(){localStream?.getTracks().forEach(t=>t.stop());localStream=null;document.querySelector('#local').srcObject=null;document.querySelector('#remote').srcObject=null;document.querySelector('#self-empty').classList.remove('hidden');document.querySelector('#empty').classList.remove('hidden');document.querySelector('#grid').classList.remove('live');document.querySelector('#camera').classList.remove('active');activeCall=null;status(connection?'Arkadaşın bağlandı':'Odan hazır',connection?'ok':'')}
function hangup(){activeCall?.close();resetCall()}
function mic(){const t=localStream?.getAudioTracks()[0];if(!t){toast('Mikrofonu açmak için önce ara.');return}t.enabled=!t.enabled;document.querySelector('#mic').classList.toggle('active',!t.enabled);toast(t.enabled?'Mikrofon açık':'Mikrofon kapalı')}
function camera(){if(activeCall){toast('Kamerayı arama sırasında kapatıp açabilirsin.');const t=localStream?.getVideoTracks()[0];if(t){t.enabled=!t.enabled;document.querySelector('#camera').classList.toggle('active',!t.enabled)}return}call(true)}
function stop(){try{activeCall?.close();connection?.close();peer?.destroy()}catch{}localStream?.getTracks().forEach(t=>t.stop())}
function toast(text,error=false){const e=document.querySelector('#toast');e.textContent=text;e.classList.toggle('error',error);e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),3300)}

login();


