
import { auth, db, googleProvider, firebaseConfigured } from './firebase.js';
import { signInWithPopup, signInWithRedirect, getRedirectResult, onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { collection, doc, getDoc, getDocs, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, addDoc, where } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';

const app = document.querySelector('#app');
let currentUser = null, selectedUser = null, stopChats = null, stopMessages = null, stopUsers = null, stopIncoming = null;
let localStream = null, peer = null, currentCallId = null, callDocUnsub = null, candidateUnsubs = [], pendingCandidates = [], ringingCall = null;
const initials = name => (name || '?').trim().split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase();
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const chatIdFor = (a,b) => [a,b].sort().join('_');
const dateLabel = value => { if(!value) return ''; const d=value.toDate?value.toDate():new Date(value); return new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'}).format(d); };
const notify = (message, error=false) => { const el=document.querySelector('#toast'); if(!el)return; el.textContent=message; el.classList.toggle('error',error); el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),3600); };
function showLogin(message='') {
  app.innerHTML = `<main class="login-shell"><section class="login-art"><div class="art-orb"></div><div class="art-copy"><span class="brand-mark">D<span>.</span></span><p class="eyebrow">MESAFE SADECE BİR DETAY</p><h1>Yakınlık,<br><i>bağlantıda</i><br>kalınca başlar.</h1><p class="art-sub">Konuş. Görüş. Paylaş. Sevdiklerinle aynı anda, aynı yerdeymiş gibi.</p><div class="art-bottom">DERİN İLETİŞİM · 01 / 26</div></div></section><section class="login-panel"><div class="login-top"><span class="brand-mark dark">D<span>.</span></span><span class="status-dot">● &nbsp; Canlı bağlantı</span></div><div class="login-card"><p class="eyebrow">DERİN'E HOŞ GELDİN</p><h2>Bağlantı kur.</h2><p class="muted">Google hesabınla giriş yap, konuşmaya başlayalım.</p><button class="google-button" id="google-login"><span class="google-g">G</span><span>Google ile devam et</span><span class="arrow">↗</span></button>${message?`<p class="login-error">${escapeHtml(message)}</p>`:''}<div class="login-note"><span>◈</span> Hesabın güvenli Google oturumu ile doğrulanır.</div></div><div class="login-footer">GİRİŞ YAPARAK KULLANIM KOŞULLARINI KABUL EDERSİN.</div></section><div id="toast" class="toast"></div></main>`;
  document.querySelector('#google-login').onclick=async()=>{try{await signInWithPopup(auth,googleProvider)}catch(e){if(e.code==='auth/popup-blocked'){await signInWithRedirect(auth,googleProvider);return}notify(authMessage(e),true)}};
}
function showFirebaseSetup(){app.innerHTML=`<main class="login-shell"><section class="login-art"><div class="art-orb"></div><div class="art-copy"><span class="brand-mark">D<span>.</span></span><p class="eyebrow">SON BİR BAĞLANTI</p><h1>Derin'i<br><i>hazırlayalım.</i></h1><p class="art-sub">Site yayınlandı. Google girişini ve sohbeti açmak için Firebase bilgilerini ekle.</p><div class="art-bottom">DERİN İLETİŞİM · 01 / 26</div></div></section><section class="login-panel"><div class="login-top"><span class="brand-mark dark">D<span>.</span></span><span class="status-dot">● Site yayında</span></div><div class="login-card"><p class="eyebrow">FIREBASE BAĞLANTISI GEREKİYOR</p><h2>Kurulum tamamlanıyor.</h2><p class="muted">1. Firebase Console'da web uygulaması oluştur.<br>2. Google Authentication ve Firestore'u etkinleştir.<br>3. Firebase web ayarlarını <code>src/firebase-config.js</code> dosyasına yaz.<br>4. <code>firestore.rules</code> kurallarını yayınla.<br>5. Değişiklikleri GitHub'a gönder.</p><a class="google-button setup-readme" href="https://firebase.google.com/console/" target="_blank" rel="noreferrer">Firebase Console'u aç <span class="arrow">↗</span></a><div class="login-note"><span>◈</span> Bu site GitHub Pages'te çalışır. Mesaj ve aramalar Firebase üzerinden eşitlenir.</div></div><div class="login-footer">FIREBASE WEB SDK · WEBRTC</div></section></main>`}
function authMessage(e){return e.code==='auth/unauthorized-domain'?'Firebase Console > Authentication > Settings bölümünden bu adresi yetkili alanlara ekle.':(e.message||'Giriş başarısız oldu.')}
function renderShell(){
 app.innerHTML=`<main class="workspace"><aside class="rail"><a class="brand-mark" href="#">D<span>.</span></a><button class="rail-icon active" title="Mesajlar">▤</button><button class="rail-icon" title="Kişiler" id="people-shortcut">♙</button><div class="rail-bottom"><button class="rail-icon" title="Yardım">?</button><button class="avatar rail-avatar" id="profile-button" title="Çıkış yap">${currentUser.photoURL?`<img src="${escapeHtml(currentUser.photoURL)}" alt="">`:initials(currentUser.displayName)}</button></div></aside><aside class="sidebar"><header class="side-header"><div><p class="eyebrow">DERİN MESAJLAR</p><h1>Gelen kutusu</h1></div><button id="signout" class="icon-button" title="Çıkış yap">↗</button></header><label class="search"><span>⌕</span><input id="search" placeholder="İsim veya e-posta ara" autocomplete="off"><kbd>⌘ K</kbd></label><div class="section-label"><span>SON SOHBETLER</span><button id="refresh-users" title="Kişileri yenile">＋</button></div><div id="chat-list" class="chat-list"><div class="empty-small">Kişiler yükleniyor…</div></div><div class="side-bottom"><div class="secure-note"><span>◈</span><span>Google hesabınla giriş yaptın.<br><small>Güvenli bağlantı aktif</small></span><i></i></div></div></aside><section class="main-panel" id="main-panel"><div class="welcome"><div class="welcome-art"><div class="welcome-circle">D<span>.</span></div><span class="orbit orbit-a"></span><span class="orbit orbit-b"></span></div><p class="eyebrow">HER ŞEY BİR MERHABA İLE BAŞLAR</p><h2>Birini seç.<br><i>Bağlantı kur.</i></h2><p class="muted">Sohbet etmek için soldan bir kişi seç<br>ya da arama kutusunda bul.</p><div class="welcome-user"><div class="avatar">${currentUser.photoURL?`<img src="${escapeHtml(currentUser.photoURL)}" alt="">`:initials(currentUser.displayName)}</div><span>${escapeHtml(currentUser.displayName||'')}</span><b>● ÇEVRİM İÇİ</b></div></div></section><aside class="right-rail"><div class="right-label">ŞU AN</div><div class="now-card"><span class="live-pulse"></span><div><strong>Canlı bağlantı</strong><small>Ses & video hazır</small></div></div><div class="ambient"><span>“</span><p>Uzaklık, sesini duymadığım zamandır.</p><small>DERİN'DEN NOTLAR</small></div><div class="right-bottom">GİZLİLİK &nbsp; · &nbsp; YARDIM</div></aside><div id="toast" class="toast"></div><section id="call-overlay" class="call-overlay hidden"></section><section id="incoming-overlay" class="incoming-overlay hidden"></section></main>`;
 document.querySelector('#signout').onclick=()=>signOut(auth).catch(e=>notify(e.message,true));
 document.querySelector('#profile-button').onclick=()=>{if(confirm('Hesabından çıkış yapmak istiyor musun?'))signOut(auth)};
 document.querySelector('#refresh-users').onclick=loadUsers;
 document.querySelector('#search').addEventListener('input',e=>filterUsers(e.target.value));
 document.querySelector('#people-shortcut').onclick=()=>{document.querySelector('#search').focus();loadUsers()};
 loadUsers(); listenChats(); listenIncomingCalls();
}
async function loadUsers(){
 if(!currentUser)return; try{const snap=await getDocs(query(collection(db,'users'),orderBy('displayName'),limit(100))); const users=snap.docs.map(d=>({uid:d.id,...d.data()})).filter(u=>u.uid!==currentUser.uid); window.derinUsers=users; renderUserList(users)}catch(e){notify('Kişiler yüklenemedi: '+e.message,true)}
}
function renderUserList(users){const list=document.querySelector('#chat-list');if(!list)return; const chats=window.derinChats||[];const byId=new Map(chats.map(c=>[c.other.uid,c])); const sorted=[...users].sort((a,b)=>Number(byId.has(b.uid))-Number(byId.has(a.uid)));if(!sorted.length){list.innerHTML='<div class="empty-small">Henüz başka kullanıcı yok.<br>Bir arkadaşın giriş yaptığında burada görünür.</div>';return}list.innerHTML=sorted.map(u=>{const c=byId.get(u.uid),active=selectedUser?.uid===u.uid;return `<button class="person-row ${active?'selected':''}" data-uid="${escapeHtml(u.uid)}"><span class="avatar">${u.photoURL?`<img src="${escapeHtml(u.photoURL)}" alt="">`:initials(u.displayName)}</span><span class="person-info"><strong>${escapeHtml(u.displayName||'Google kullanıcısı')}</strong><small>${escapeHtml(c?.lastMessage||u.email||'Sohbet başlat')}</small></span><span class="person-meta">${c?.updatedAt?dateLabel(c.updatedAt):''}<i></i></span></button>`}).join('');list.querySelectorAll('.person-row').forEach(row=>row.onclick=()=>{const u=(window.derinUsers||[]).find(x=>x.uid===row.dataset.uid);if(u)openChat(u)})}
function filterUsers(value){const q=value.trim().toLocaleLowerCase('tr');renderUserList((window.derinUsers||[]).filter(u=>(u.displayName||'').toLocaleLowerCase('tr').includes(q)||(u.email||'').toLocaleLowerCase('tr').includes(q)))}
function listenChats(){if(stopChats)stopChats();stopChats=onSnapshot(query(collection(db,'chats'),where('members','array-contains',currentUser.uid)),snap=>{window.derinChats=snap.docs.map(d=>{const x=d.data(),otherId=x.members.find(id=>id!==currentUser.uid);return{...x,id:d.id,other:(window.derinUsers||[]).find(u=>u.uid===otherId)||{uid:otherId,displayName:'Kullanıcı'}}}).sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));if(window.derinUsers)renderUserList(window.derinUsers)},e=>notify('Sohbetler alınamadı: '+e.message,true))}
async function openChat(user){selectedUser=user;renderUserList(window.derinUsers||[]);const id=chatIdFor(currentUser.uid,user.uid),ref=doc(db,'chats',id);try{await setDoc(ref,{members:[currentUser.uid,user.uid].sort(),lastMessage:'',updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true})}catch(e){notify('Sohbet açılamadı: '+e.message,true);return}if(stopMessages)stopMessages();const panel=document.querySelector('#main-panel');panel.innerHTML=`<div class="chat-view"><header class="chat-header"><div class="chat-person"><span class="avatar">${user.photoURL?`<img src="${escapeHtml(user.photoURL)}" alt="">`:initials(user.displayName)}</span><div><strong>${escapeHtml(user.displayName||'Google kullanıcısı')}</strong><small><i></i> Bağlantı kurmaya hazır</small></div></div><div class="chat-actions"><button class="call-button" id="audio-call" title="Sesli ara">☎</button><button class="call-button video" id="video-call" title="Görüntülü ara">▣</button><button class="icon-button more" title="Diğer seçenekler">···</button></div></header><div class="messages" id="messages"><div class="date-divider"><span>SOHBET BAŞLANGICI</span></div><div class="message-hint">Buradaki mesajlar anlık olarak senkronize edilir.</div></div><form class="composer" id="composer"><button type="button" class="attach" title="Ekler yakında">＋</button><input id="message-input" placeholder="Bir mesaj yaz…" maxlength="2000" autocomplete="off"><button class="send-button" type="submit" aria-label="Gönder">↑</button><small>↵ GÖNDER</small></form></div>`;
 document.querySelector('#audio-call').onclick=()=>startCall(user,false);document.querySelector('#video-call').onclick=()=>startCall(user,true);
 document.querySelector('#composer').onsubmit=async e=>{e.preventDefault();const input=document.querySelector('#message-input'),text=input.value.trim();if(!text)return;input.value='';try{const messages=collection(db,'chats',id,'messages');await addDoc(messages,{text,authorUid:currentUser.uid,createdAt:serverTimestamp()});await updateDoc(ref,{lastMessage:text,updatedAt:serverTimestamp()})}catch(err){notify('Mesaj gönderilemedi: '+err.message,true);input.value=text}};
 stopMessages=onSnapshot(query(collection(db,'chats',id,'messages'),orderBy('createdAt'),limit(300)),snap=>{const box=document.querySelector('#messages');if(!box)return;box.innerHTML='<div class="date-divider"><span>SOHBET BAŞLANGICI</span></div>'+snap.docs.map(d=>{const m=d.data(),mine=m.authorUid===currentUser.uid;return `<div class="message-line ${mine?'mine':''}"><div class="bubble">${escapeHtml(m.text)}<small>${dateLabel(m.createdAt)}</small></div></div>`}).join('');box.scrollTop=box.scrollHeight},e=>notify('Mesajlar yüklenemedi: '+e.message,true));
}
function listenIncomingCalls(){stopIncoming=onSnapshot(query(collection(db,'calls'),where('calleeUid','==',currentUser.uid)),snap=>{const call=snap.docs.find(d=>d.data().status==='ringing');if(!call){if(ringingCall&&!currentCallId){ringingCall=null;document.querySelector('#incoming-overlay')?.classList.add('hidden')}return}if(ringingCall===call.id)return;ringingCall=call.id;showIncoming(call.id,call.data())},e=>console.error(e));}
function showIncoming(id,data){const el=document.querySelector('#incoming-overlay');if(!el)return;const caller=(window.derinUsers||[]).find(u=>u.uid===data.callerUid);el.classList.remove('hidden');el.innerHTML=`<div class="incoming-card"><span class="incoming-glow"></span><div class="avatar big">${caller?.photoURL?`<img src="${escapeHtml(caller.photoURL)}" alt="">`:initials(caller?.displayName||'D')}</div><p class="eyebrow">GELEN ${data.video?'GÖRÜNTÜLÜ':'SESLİ'} ARAMA</p><h2>${escapeHtml(caller?.displayName||'Bir kişi')} arıyor…</h2><p>Yanıtlamak için yeşil düğmeye dokun.</p><div class="incoming-actions"><button id="decline-call" class="call-control decline">✕</button><button id="accept-call" class="call-control accept">☎</button></div></div>`;document.querySelector('#accept-call').onclick=()=>acceptCall(id,data);document.querySelector('#decline-call').onclick=()=>declineCall(id)}
async function getMedia(video){localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video?{width:{ideal:1280},height:{ideal:720}}:false});return localStream}
function newPeer(video){peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});localStream.getTracks().forEach(track=>peer.addTrack(track,localStream));peer.ontrack=e=>{const remote=document.querySelector('#remote-video');if(remote)remote.srcObject=e.streams[0]};peer.onconnectionstatechange=()=>{if(['failed','disconnected'].includes(peer?.connectionState))notify('Bağlantı kesildi. Ağını kontrol et.',true)};showCallOverlay(video);return peer}
function showCallOverlay(video){const el=document.querySelector('#call-overlay');el.classList.remove('hidden');el.innerHTML=`<div class="call-stage"><div class="call-top"><span class="brand-mark">D<span>.</span></span><span id="call-status">Bağlantı kuruluyor…</span><button id="end-call-top" class="icon-button">×</button></div><div class="remote-wrap"><video id="remote-video" autoplay playsinline></video><div id="remote-placeholder" class="remote-placeholder"><div class="avatar big">◌</div><p>Karşı tarafın görüntüsü bekleniyor</p></div><div class="video-label" id="remote-label">DERİN BAĞLANTI</div></div><video id="local-video" class="local-video" autoplay playsinline muted></video><div class="call-controls"><button id="mute-call" class="call-control" title="Mikrofonu kapat">♬</button>${video?'<button id="camera-call" class="call-control" title="Kamerayı kapat">▣</button>':'<button id="camera-call" class="call-control" title="Kamerayı aç">◉</button>'}<button id="hangup-call" class="call-control decline" title="Aramayı bitir">☎</button></div><div class="call-foot">${video?'GÖRÜNTÜLÜ ARAMA':'SESLİ ARAMA'} &nbsp; · &nbsp; UÇTAN UCA WEBRTC BAĞLANTISI</div></div>`;document.querySelector('#end-call-top').onclick=endCall;document.querySelector('#hangup-call').onclick=endCall;document.querySelector('#mute-call').onclick=e=>{if(localStream){const t=localStream.getAudioTracks()[0];t.enabled=!t.enabled;e.currentTarget.classList.toggle('off',!t.enabled)}};document.querySelector('#camera-call').onclick=e=>{if(localStream){let t=localStream.getVideoTracks()[0];if(!t){notify('Bu arama sesli. Görüntü için görüntülü arama başlat.');return}t.enabled=!t.enabled;e.currentTarget.classList.toggle('off',!t.enabled)}};}
async function startCall(user,video){try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera ve mikrofon için localhost veya HTTPS kullan.');await getMedia(video);const pc=newPeer(video);document.querySelector('#local-video').srcObject=localStream;const ref=await addDoc(collection(db,'calls'),{callerUid:currentUser.uid,calleeUid:user.uid,callerName:currentUser.displayName||'Kullanıcı',video,status:'ringing',participants:[currentUser.uid,user.uid],createdAt:serverTimestamp()});currentCallId=ref.id;pc.onicecandidate=e=>{if(e.candidate)addDoc(collection(db,'calls',ref.id,'offerCandidates'),e.candidate.toJSON()).catch(console.error)};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await updateDoc(ref,{offer:{type:offer.type,sdp:offer.sdp}});watchCall(ref.id,true);notify('Aranıyor: '+(user.displayName||'kullanıcı'))}catch(e){notify('Arama başlatılamadı: '+e.message,true);await cleanupCall()}}
function watchCall(id,isCaller){const ref=doc(db,'calls',id);callDocUnsub=onSnapshot(ref,async snap=>{if(!snap.exists())return;const data=snap.data();if(data.status==='ended'){notify('Arama sona erdi.');cleanupCall();return}if(isCaller&&data.answer&&!peer?.currentRemoteDescription){try{await peer.setRemoteDescription(new RTCSessionDescription(data.answer));for(const c of pendingCandidates.splice(0))await peer.addIceCandidate(c).catch(console.error);document.querySelector('#call-status').textContent='Bağlandı';document.querySelector('#remote-placeholder')?.classList.add('hidden')}catch(e){console.error(e)}}},e=>notify('Arama bağlantısı koptu: '+e.message,true));const candidates=collection(db,'calls',id,isCaller?'answerCandidates':'offerCandidates');candidateUnsubs.push(onSnapshot(candidates,snap=>snap.docChanges().forEach(async change=>{if(change.type!=='added'||!peer)return;const candidate=new RTCIceCandidate(change.doc.data());if(peer.remoteDescription)peer.addIceCandidate(candidate).catch(console.error);else pendingCandidates.push(candidate)})));}
async function acceptCall(id,data){try{document.querySelector('#incoming-overlay').classList.add('hidden');if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera ve mikrofon için localhost veya HTTPS kullan.');await getMedia(data.video);const pc=newPeer(data.video);document.querySelector('#local-video').srcObject=localStream;currentCallId=id;const callRef=doc(db,'calls',id),snap=await getDoc(callRef);if(!snap.exists())throw Error('Arama artık mevcut değil.');await pc.setRemoteDescription(new RTCSessionDescription(snap.data().offer));for(const c of pendingCandidates.splice(0))await pc.addIceCandidate(c).catch(console.error);pc.onicecandidate=e=>{if(e.candidate)addDoc(collection(db,'calls',id,'answerCandidates'),e.candidate.toJSON()).catch(console.error)};const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await updateDoc(callRef,{answer:{type:answer.type,sdp:answer.sdp},status:'connected'});watchCall(id,false);document.querySelector('#call-status').textContent='Bağlandı';document.querySelector('#remote-placeholder')?.classList.add('hidden')}catch(e){notify('Arama yanıtlanamadı: '+e.message,true);await cleanupCall()}}
async function declineCall(id){try{await updateDoc(doc(db,'calls',id),{status:'ended'})}catch{}document.querySelector('#incoming-overlay').classList.add('hidden');ringingCall=null}
async function endCall(){if(currentCallId)try{await updateDoc(doc(db,'calls',currentCallId),{status:'ended'})}catch{}await cleanupCall()}
async function cleanupCall(){if(callDocUnsub){callDocUnsub();callDocUnsub=null}candidateUnsubs.forEach(u=>u());candidateUnsubs=[];pendingCandidates=[];if(peer){peer.ontrack=null;peer.close();peer=null}if(localStream){localStream.getTracks().forEach(t=>t.stop());localStream=null}currentCallId=null;ringingCall=null;document.querySelector('#call-overlay')?.classList.add('hidden');document.querySelector('#incoming-overlay')?.classList.add('hidden')}
if(firebaseConfigured){
getRedirectResult(auth).catch(e=>showLogin(authMessage(e)));
onAuthStateChanged(auth,async user=>{if(!user){currentUser=null;if(stopChats)stopChats();if(stopMessages)stopMessages();if(stopIncoming)stopIncoming();await cleanupCall();showLogin();return}currentUser=user;try{await setDoc(doc(db,'users',user.uid),{displayName:user.displayName||'Google kullanıcısı',photoURL:user.photoURL||'',updatedAt:serverTimestamp()},{merge:true})}catch(e){console.error(e);showLogin('Profil hazırlanamadı. Firestore kurallarını kurulum rehberindeki gibi yayınla.');return}renderShell()});
}else{showFirebaseSetup()}







